apiVersion: v2
name: health-platform
description: Health Data AI Platform - Complete deployment for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - health-data
  - ai
  - machine-learning
  - webauthn
  - healthcare
  - kubernetes

home: https://github.com/hitoshura25/health-data-ai-platform
sources:
  - https://github.com/hitoshura25/health-data-ai-platform

maintainers:
  - name: Health Data AI Platform Team
    email: hitoshura25@users.noreply.github.com

dependencies:
  # Module 2: Infrastructure layer (PostgreSQL, Redis, MinIO, RabbitMQ)
  - name: infrastructure
    version: 1.0.0
    repository: file://./charts/infrastructure
    condition: infrastructure.enabled

  # Module 3: WebAuthn Stack (authentication)
  - name: webauthn-stack
    version: 1.0.0
    repository: file://./charts/webauthn-stack
    condition: webauthn-stack.enabled

  # Module 4: Health API Service
  - name: health-api
    version: 1.0.0
    repository: file://./charts/health-api
    condition: health-api.enabled

  # Module 4: ETL Narrative Engine
  - name: etl-engine
    version: 1.0.0
    repository: file://./charts/etl-engine
    condition: etl-engine.enabled

  # Module 5: Observability Stack (Prometheus, Grafana, Jaeger, Loki)
  - name: observability
    version: 1.0.0
    repository: file://./charts/observability
    condition: observability.enabled

annotations:
  # Helm chart metadata
  category: Healthcare
  licenses: MIT

  # Oracle Cloud specific
  cloud.oracle.com/platform: oke
  cloud.oracle.com/tier: always-free
  cloud.oracle.com/region: eu-amsterdam-1

  # Resource requirements (Complete Platform - Modules 1-5)
  # NOTE: Default production config (values-production.yaml) EXCEEDS Always Free tier
  cloud.oracle.com/cpu-request: "4550m"  # Production HA config
  cloud.oracle.com/memory-request: "10.6Gi"
  cloud.oracle.com/storage-request: "231Gi"

  # Oracle Always Free tier optimized config (values-oracle-free-tier.yaml)
  cloud.oracle.com/cpu-request-free-tier: "3450m"  # Single replicas, minimal observability
  cloud.oracle.com/memory-request-free-tier: "7.9Gi"
  cloud.oracle.com/storage-request-free-tier: "194Gi"
