apiVersion: v2
name: health-platform
description: Health Data AI Platform - Complete deployment for Kubernetes
type: application
version: 1.0.0
appVersion: "1.0.0"

keywords:
  - health-data
  - ai
  - machine-learning
  - webauthn
  - healthcare
  - kubernetes

home: https://github.com/hitoshura25/health-data-ai-platform
sources:
  - https://github.com/hitoshura25/health-data-ai-platform

maintainers:
  - name: Health Data AI Platform Team
    email: hitoshura25@users.noreply.github.com

# Note: Subcharts are automatically discovered from charts/ directory
# No explicit dependencies declaration needed for local subcharts in Helm 3
# Enable/disable subcharts using values.yaml with <subchart-name>.enabled: true/false

annotations:
  # Helm chart metadata
  category: Healthcare
  licenses: MIT

  # Oracle Cloud specific
  cloud.oracle.com/platform: oke
  cloud.oracle.com/tier: always-free
  cloud.oracle.com/region: eu-amsterdam-1

  # Resource requirements
  cloud.oracle.com/cpu-request: "1150m"
  cloud.oracle.com/memory-request: "3Gi"
  cloud.oracle.com/storage-request: "185Gi"
