apiVersion: v2
name: argocd
description: ArgoCD installation chart for Health Data AI Platform GitOps
type: application
version: 1.0.0
appVersion: "2.10.0"
keywords:
  - argocd
  - gitops
  - continuous-deployment
maintainers:
  - name: Health Data AI Platform Team
dependencies:
  - name: argo-cd
    version: "5.51.6"
    repository: https://argoproj.github.io/argo-helm
