# Health Data API Service
# Secure health data upload and processing API
services:
  health-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: health-api
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${HEALTH_API_PORT:-8000}:8000"
    environment:
      # Application
      - SECRET_KEY=${SECRET_KEY}

      # Database
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${HEALTH_API_DB:-healthapi}

      # Redis (for rate limiting)
      - REDIS_URL=redis://:${HEALTH_REDIS_PASSWORD}@redis:6379
      - UPLOAD_RATE_LIMIT_STORAGE_URI=redis://:${HEALTH_REDIS_PASSWORD}@redis:6379

      # S3/MinIO (for file storage)
      - S3_ENDPOINT_URL=http://minio:9000
      - S3_ACCESS_KEY=${DATALAKE_MINIO_ACCESS_KEY:-minioadmin}
      - S3_SECRET_KEY=${DATALAKE_MINIO_SECRET_KEY:-minioadmin}
      - S3_BUCKET_NAME=${DATALAKE_BUCKET_NAME:-health-data}

      # RabbitMQ (for message queue)
      - RABBITMQ_URL=amqp://${MQ_RABBITMQ_USER:-guest}:${MQ_RABBITMQ_PASS:-guest}@rabbitmq:5672/
      - RABBITMQ_MAIN_EXCHANGE=${RABBITMQ_MAIN_EXCHANGE:-health-data}

      # Jaeger Distributed Tracing (points to webauthn-stack Jaeger)
      - JAEGER_OTLP_ENDPOINT=http://host.docker.internal:4319
      - JAEGER_SERVICE_NAME=health-api-service

      # WebAuthn Integration (for token exchange via JWKS)
      - WEBAUTHN_JWKS_URL=${WEBAUTHN_JWKS_URL:-http://host.docker.internal:8000/.well-known/jwks.json}
      - WEBAUTHN_JWKS_CACHE_LIFESPAN=${WEBAUTHN_JWKS_CACHE_LIFESPAN:-300}
      - WEBAUTHN_ISSUER=mpo-webauthn
      - SSO_USER_EMAIL_DOMAIN=${SSO_USER_EMAIL_DOMAIN:-sso.example.com}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      minio:
        condition: service_healthy
      data-lake-setup:
        condition: service_completed_successfully
      rabbitmq:
        condition: service_healthy
    networks:
      - health-platform-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped
