# GitHub Workflow Template for Health Data AI Platform Services
# Copy this file to .github/workflows/your-service-name.yml and customize

name: Your Service Name CI/CD

on:
  push:
    paths:
      - 'services/your-service-name/**'
      - 'shared/**'
      - '.github/workflows/your-service-name.yml'
  pull_request:
    paths:
      - 'services/your-service-name/**'
      - 'shared/**'

env:
  SERVICE_NAME: your-service-name
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/your-service-name

jobs:
  test:
    runs-on: ubuntu-latest

    # Add services your service depends on for testing
    services:
      # For database-dependent services
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      # For cache-dependent services
      redis:
        image: redis:7-alpine
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

      # For message queue services
      rabbitmq:
        image: rabbitmq:3.13-management
        env:
          RABBITMQ_DEFAULT_USER: test_user
          RABBITMQ_DEFAULT_PASS: test_password
          RABBITMQ_DEFAULT_VHOST: test_vhost
        options: >-
          --health-cmd "rabbitmq-diagnostics check_port_connectivity"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5672:5672
          - 15672:15672

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('services/your-service-name/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        cd services/${{ env.SERVICE_NAME }}
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest pytest-asyncio pytest-cov pytest-httpx

    - name: Lint with flake8
      run: |
        cd services/${{ env.SERVICE_NAME }}
        pip install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Type check with mypy
      run: |
        cd services/${{ env.SERVICE_NAME }}
        pip install mypy
        mypy . --ignore-missing-imports

    - name: Wait for services to be ready
      run: |
        # Wait for PostgreSQL
        timeout 60 bash -c 'until pg_isready -h localhost -p 5432 -U test_user; do sleep 2; done'

        # Wait for Redis
        timeout 60 bash -c 'until redis-cli -h localhost ping; do sleep 2; done'

        # Wait for RabbitMQ (if needed)
        timeout 60 bash -c 'until curl -f http://localhost:15672; do sleep 2; done'

    - name: Run tests
      env:
        # Customize environment variables for your service
        DATABASE_URL: postgresql://test_user:test_password@localhost:5432/test_db
        REDIS_URL: redis://localhost:6379
        RABBITMQ_URL: amqp://test_user:test_password@localhost:5672/test_vhost
        SECRET_KEY: test-secret-key
        ENVIRONMENT: test
      run: |
        cd services/${{ env.SERVICE_NAME }}
        pytest --cov=app --cov-report=xml --cov-report=term-missing -v

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: services/${{ env.SERVICE_NAME }}/coverage.xml
        flags: ${{ env.SERVICE_NAME }}
        name: ${{ env.SERVICE_NAME }}-coverage

  security-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run Bandit security scan
      run: |
        cd services/${{ env.SERVICE_NAME }}
        pip install bandit
        bandit -r . -f json -o bandit-report.json || true

    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: bandit-report-${{ env.SERVICE_NAME }}
        path: services/${{ env.SERVICE_NAME }}/bandit-report.json

  build:
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: services/${{ env.SERVICE_NAME }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

  # Uncomment and customize for staging deployment
  # deploy-staging:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/develop'
  #   environment: staging
  #
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #
  #   - name: Set up kubectl
  #     uses: azure/setup-kubectl@v3
  #     with:
  #       version: 'latest'
  #
  #   - name: Configure kubectl
  #     run: |
  #       echo "${{ secrets.KUBE_CONFIG_STAGING }}" | base64 -d > kubeconfig
  #       export KUBECONFIG=kubeconfig
  #
  #   - name: Deploy to staging
  #     run: |
  #       export KUBECONFIG=kubeconfig
  #       kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop-${{ github.sha }} -n health-staging
  #       kubectl rollout status deployment/${{ env.SERVICE_NAME }} -n health-staging

  # Uncomment and customize for production deployment
  # deploy-production:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   if: github.ref == 'refs/heads/main'
  #   environment: production
  #
  #   steps:
  #   - name: Checkout code
  #     uses: actions/checkout@v4
  #
  #   - name: Set up kubectl
  #     uses: azure/setup-kubectl@v3
  #     with:
  #       version: 'latest'
  #
  #   - name: Configure kubectl
  #     run: |
  #       echo "${{ secrets.KUBE_CONFIG_PRODUCTION }}" | base64 -d > kubeconfig
  #       export KUBECONFIG=kubeconfig
  #
  #   - name: Deploy to production
  #     run: |
  #       export KUBECONFIG=kubeconfig
  #       kubectl set image deployment/${{ env.SERVICE_NAME }} ${{ env.SERVICE_NAME }}=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:main-${{ github.sha }} -n health-production
  #       kubectl rollout status deployment/${{ env.SERVICE_NAME }} -n health-production