# Shared Redis cache and session store
# Used by: health-api-service (rate limiting), webauthn-server (sessions), message-queue
services:
  redis:
    image: redis:7-alpine
    container_name: health-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes --requirepass ${WEBAUTHN_REDIS_PASSWORD}
    healthcheck:
      test: ["CMD", "redis-cli", "--pass", "${WEBAUTHN_REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3
    networks:
      - health-platform-net
    restart: unless-stopped

volumes:
  redis_data:
    driver: local
