# MPO WebAuthn Authentication Server
# Passkey-based authentication service (from external repo: mpo-api-authn-server)
# Configuration reference: https://raw.githubusercontent.com/hitoshura25/mpo-api-authn-server/main/.ai-agents.json
services:
  webauthn-server:
    image: hitoshura25/webauthn-server:${WEBAUTHN_VERSION:-latest}
    container_name: health-webauthn
    ports:
      - "${WEBAUTHN_PORT:-8080}:8080"
    environment:
      # PostgreSQL Database Connection
      - MPO_AUTHN_DB_HOST=postgres
      - MPO_AUTHN_DB_PORT=5432
      - MPO_AUTHN_DB_NAME=${WEBAUTHN_DB:-webauthn}
      - MPO_AUTHN_DB_USERNAME=${POSTGRES_USER:-postgres}
      - MPO_AUTHN_DB_PASSWORD=${POSTGRES_PASSWORD:-postgres}

      # Redis Session Storage
      - MPO_AUTHN_REDIS_HOST=redis
      - MPO_AUTHN_REDIS_PORT=6379
      - MPO_AUTHN_REDIS_PASSWORD=${WEBAUTHN_REDIS_PASSWORD}

      # WebAuthn Relying Party Configuration
      - MPO_AUTHN_APP_RELYING_PARTY_ID=${WEBAUTHN_RP_ID:-localhost}
      - MPO_AUTHN_APP_RELYING_PARTY_NAME=${WEBAUTHN_RP_NAME:-Health Data Platform}

      # OpenTelemetry / Jaeger Tracing (optional)
      - MPO_AUTHN_OPEN_TELEMETRY_SERVICE_NAME=health-webauthn
      - MPO_AUTHN_OPEN_TELEMETRY_JAEGER_ENDPOINT=http://jaeger:4317
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      jaeger:
        condition: service_started
    networks:
      - health-platform-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
